### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by zeffii** [zeffii/pyBLOK#2]
In no specific order.
- [x] overload `>` to mean  
     to connect units do
  
  ``` python
     env > osc.index(1)
     osc > out.index(1)
  ```
  
     or  
  
  ``` python
     env > (osc, 1)
     osc > (out, 1)
  ```
- [x] helper function (Hz to unit 0.0...1.0)
- [x] dynamic getter / setter for BLOK units, f.ex `Env1.decay(0.2)`.
- [ ] supply several preset envelopes for Custom Envelope
- [ ] supply some kind of bezier directive for Custom Envelopes float-vector array
- [ ] Sublime autocomplete / snippets?
- [ ] generate automatic DAG X,Y positions (may be slightly tricky with multiple outs)
- [ ] ensure absolute P values only. clamped 0.0...1.0
- [ ] more?
